# =================================================================
# FRANQUICIAS API - APPLICATION CONFIGURATION
# =================================================================

# Server Configuration
server:
  port: 8080
  shutdown: graceful

# Spring Application
spring:
  application:
    name: franquicias-api
  
  # R2DBC Configuration
  r2dbc:
    url: r2dbc:mysql://localhost:3306/franquicias_db
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    pool:
      initial-size: 10
      max-size: 20
      max-idle-time: 30m
      validation-query: SELECT 1
  
  # Flyway Configuration (for schema management)
  flyway:
    enabled: true
    url: jdbc:mysql://localhost:3306/franquicias_db?createDatabaseIfNotExist=true
    user: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    locations: classpath:db/migration
    baseline-on-migrate: true
  
  # Jackson Configuration
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

# Management (Actuator)
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      cors:
        allowed-origins: "*"
        allowed-methods: GET,POST
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true

# Logging Configuration
logging:
  level:
    com.nequi.franquicias: INFO
    org.springframework.r2dbc: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/franquicias-api.log

# OpenAPI Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  show-actuator: true
